name: Acquire activation file for Windows
# Run manually when initializing the workflow or to update the Windows license
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Request manual activation file ðŸ”‘
    runs-on: windows-latest
    steps:
      # Checkout repo in the Github workspace
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Unity
        uses: kuler90/setup-unity@v1.0.8
        with:
          unity-version: 2020.3.38f1

      # Request manual activation file
      - name: Request manual activation file
        run: ci\get_windows_activation_file.bat
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: License artifacts
          path: artifacts\
